In [4]:
import numpy as np

In [15]:
npa = np.array(range(10))
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
type(npa)

numpy.ndarray

In [21]:
npa[1]

1

In [19]:
## Trae el elemento de index 1, contando desde el final
npa[-1]

9

In [10]:
np_cero = np.zeros(10)
np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np_cero_int = np.zeros(10, dtype=int)
np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np_uno = np.ones(10, dtype=int)
np_uno

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Ceros**

In [23]:
v2 = np.zeros(20, dtype = int)
v2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Unos**

In [27]:
v3 = np.ones(20, dtype=int)
v3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Random**

In [32]:
np.random.random(30)

array([0.80079839, 0.46010998, 0.39953512, 0.56934401, 0.56359204,
       0.58715515, 0.87988899, 0.80861404, 0.03566923, 0.62863049,
       0.24849478, 0.80513408, 0.65644783, 0.23991645, 0.99699813,
       0.05955837, 0.09527663, 0.43648543, 0.80111358, 0.63761606,
       0.93168067, 0.39011858, 0.72697094, 0.58394952, 0.2183357 ,
       0.17449174, 0.61488337, 0.8842103 , 0.81152898, 0.58697782])

In [35]:
v2.dtype

dtype('int32')

**Tipos de datos**

In [37]:
v1 = np.array(['Juan', 'Pedro'])

In [38]:
v1

array(['Juan', 'Pedro'], dtype='<U5')

In [40]:
## Nos muestra el tipo de dato <U5 -> Unicode versión 5
v1.dtype

dtype('<U5')

In [43]:
arr = np.array([1.1, 2.1, 3.1])
print(arr)
arr.dtype

[1.1 2.1 3.1]


dtype('float64')

In [47]:
arr2 = arr.astype('i')
print(arr2)
arr2.dtype

[1 2 3]


dtype('int32')

In [51]:
v1 = np.array(['1','2','3'])
v1.dtype

dtype('<U1')

In [52]:
v2 = v.astype(int)
v2.dtype

dtype('int32')

**Operaciones básicas** 
##### Reshape, concatenación, splitting

**Matrices** 

In [60]:
M = np.array([[1,2,3], [4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
M.shape

(2, 3)

In [66]:
v = np.ones([10,3])
v.shape

(10, 3)

In [70]:
## Ejemplo celdas numeradas de un tablero de ajedrez
v = np.arange(1,65)

In [69]:
ajedrez_64 = np.arange(1,65).reshape(8,8)
ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [75]:
v.reshape(4,2,8)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]],

       [[17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]],

       [[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]]])

**Concatenación** 

In [86]:
v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[7,8,9],[10,11,12]])
v1

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.concatenate([v1,v2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
np.concatenate([v1,v2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [88]:
np.vstack([v1,v2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
np.hstack([v1,v2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

**Splitting** 

In [94]:
v1 = np.array([0,6,5,4,3,1,8,0,0,3])

In [96]:
v1_partido = np.split(v1, [2])
print(v1_partido)

[array([0, 6]), array([5, 4, 3, 1, 8, 0, 0, 3])]


In [97]:
v1_partido2 = np.split(v1, [2,8])
print(v1_partido2)

[array([0, 6]), array([5, 4, 3, 1, 8, 0]), array([0, 3])]


In [101]:
ajedrez_split_1 = np.hsplit(ajedrez_64, [4])
ajedrez_split_1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [125]:
ajedrez_split_2 = np.vsplit(ajedrez_64, [4])
ajedrez_split_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [127]:
ajedrez_split_2[1]

array([[33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

**Agregaciones** 

In [112]:
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [113]:
v.mean()

32.5

In [114]:
v.sum()

2080

In [115]:
v.min()

1

In [116]:
np.median(v)

32.5

**Operaciones vectoriales** 

In [117]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [118]:
v1+v2

array([5, 7, 9])

In [119]:
v1*v2

array([ 4, 10, 18])

In [121]:
v1/v2

array([0.25, 0.4 , 0.5 ])

In [122]:
## Producto vectorial
np.matmul (v1,v2)

32